x = int(input('Enter the first number: '))
y = int(input('Enter the second number: '))
x = int(x)
y = int(y)
print('Addition: ', x + y)
print('Subtraction: ', x - y)
print('Multiplication: ', x * y)
print('Division: ', x / y)